

# This file was *autogenerated* from the file th_zeri.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_100 = Integer(100); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_0p5 = RealNumber('0.5'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_2 = Integer(2); _sage_const_12 = Integer(12)
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-_sage_const_5 , _sage_const_5 , _sage_const_100 )
y = x**_sage_const_3  + _sage_const_3 *x + _sage_const_4 

plt.axhline(y=_sage_const_0 , color="green", linestyle="--")
plt.axhline(y=_sage_const_0p5 , color="black", linestyle=":")
plt.axhline(y=_sage_const_1p0 , color="red", linestyle="--")
plt.axvline(color="grey")
plt.plot(x, y, linewidth=_sage_const_2 , label=r"$f(x) = x^2 + 3x + 3$")
plt.xlim(-_sage_const_5 , _sage_const_5 )
plt.xlabel("x")
plt.legend(fontsize=_sage_const_12 )
plt.show()

